default:
  app_prod: no
  db:
    host: !expr Sys.getenv("DB_HOST")
    port: !expr Sys.getenv("DB_PORT")
    user: !expr Sys.getenv("DB_USER")
    password: !expr Sys.getenv("DB_PASSWORD")
    dbname: !expr Sys.getenv("DB_NAME")
